### PR TITLE
Refactor jsx component into ES2015

### PR DESCRIPTION
**Pull request by germ13**
Refactored `Button` component into ES2015.

No automatic transpiling done....yet.

Will add webpack-babel transpilation on future commit.

### CODE REVIEW

**Comment by aurelianonava** [comment]
Merged request.

**Comment by aurelianonava** [comment]
Juan,

Just took a look at your merge request and trying to figure out what to do
with it? I believe I merged it with the origin master already. I want you
to think about my upgrading your role to 'Event Organizer.' You'll have
full control of the group calendar and be able to communicate with all
members. It looks like we'll be working with JS.LA. David Guttman, one of
the organizers of JS.LA will be promoting our meetups with the group. Let
me know what you think. What do you think about scheduling a meetup for
next Saturday?

Aureliano

On Fri, Sep 18, 2015 at 5:54 PM, juan serrano <notifications@github.com>
wrote:

> Refactored Button component into ES2015.
>
> No automatic transpiling done....yet.
>
> Will add webpack-babel transpilation on future commit.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/aurelianonava/js-meetup/pull/3
> Commit Summary
>
>    - Merge pull request #1 from aurelianonava/master
>    - Rename js folder to components
>    - Recreate component in es2015
>    - Merge branch 'feature/es2015' into dev
>    - Merge branch 'dev'
>
> File Changes
>
>    - *A* .editorconfig
>    <https://github.com/aurelianonava/js-meetup/pull/3/files#diff-0> (17)
>    - *M* .gitignore
>    <https://github.com/aurelianonava/js-meetup/pull/3/files#diff-1> (2)
>    - *A* components/Counter.jsx
>    <https://github.com/aurelianonava/js-meetup/pull/3/files#diff-2> (28)
>    - *R* components/script.jsx
>    <https://github.com/aurelianonava/js-meetup/pull/3/files#diff-3> (2)
>    - *M* index.html
>    <https://github.com/aurelianonava/js-meetup/pull/3/files#diff-4> (4)
>    - *A* package.json
>    <https://github.com/aurelianonava/js-meetup/pull/3/files#diff-5> (30)
>
> Patch Links:
>
>    - https://github.com/aurelianonava/js-meetup/pull/3.patch
>    - https://github.com/aurelianonava/js-meetup/pull/3.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelianonava/js-meetup/pull/3>.
>



-- 
Aureliano Nava

**Comment by germ13** [comment]
Hello Aureliano.

Ok, what I did:
- Renamed `js` folder to `components` folder.  Wanted to make it less generic.
- `scripts.jsx` is stil the same.  Thats the code from your commit.
- This is the refactoring part: `Counter.jsx` and `script.jsx` functionally are the same.  I rewrote the component in the newer es2015/es6 javascript language. 
- Check out [link](http://facebook.github.io/react/blog/2015/03/10/react-v0.13.html) and [link2](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html).  Seems like Facebook might eventually phase out the previous style.  So Im just getting ready for the future, which might be soon.
- I am using the new `class` syntax and function declaration that are offered by es2015/es6, thats all.
- I have not yet added a build process to the code.

As for your offer, Ill shoot you an email in a bit. :email: 
Thanks.

**Comment by aurelianonava** [comment]
Will look at what you've added. Let me know about you taking a role in the
meetup. What do you think about a meetup next Saturday, or the one after,
Oct. 3?

On Sat, Sep 19, 2015 at 9:02 PM, juan serrano <notifications@github.com>
wrote:

> Hello Aureliano.
>
> Ok, what I did:
>
>    - Renamed js folder to components folder. Wanted to make it less
>    generic.
>    - scripts.jsx is stil the same. Thats the code from your commit.
>    - This is the refactoring part: Counter.jsx and script.jsx
>    functionally are the same. I rewrote the component in the newer es2015/es6
>    javascript language.
>    - Check out link
>    <http://facebook.github.io/react/blog/2015/03/10/react-v0.13.html> and
>    link2
>    <http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html>.
>    Seems like Facebook might eventually phase out the previous style. So Im
>    just getting ready for the future, which might be soon.
>    - I am using the new class syntax and function declaration that are
>    offered by es2015/es6, thats all.
>    - I have not yet added a build process to the code.
>
> As for your offer, Ill shoot you an email in a bit. [image: :email:]
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelianonava/js-meetup/pull/3#issuecomment-141743419>
> .
>



-- 
Aureliano Nava

**Pull request merged**
